### PR TITLE
Ecs cluster custom instances

### PR DESCRIPTION
**Pull request by backnight**
I did this to be able to push a custom "something" (cloud-init file, script, etc) to the cluster instances.
It is useful for example if you want to do extra configuration of your servers.

Example of use : 

```
// Extra configuration file for initializing cluster instances
data "template_file" "extra_config" {
  template = "${file("${path.module}/extra-setup.yml.tpl")}"

  vars {
    ...
  }
}

// Init cluster
module "stack" {
  [...]
  extra_cloud_config_content = "${data.template_file.extra_config.rendered}"
}
```

### CODE REVIEW

**Comment by backnight** [comment]
You are using an outdated version of Terraform in CircleCI (0.6.16), the current version is 0.7.5. Please change it in order to make tests possible!

**Comment by yields** [comment]
Hey do you mind re-basing master is on latest TF now? also would be nice if you kept terraform fmt out of the way, maybe it should be the last commit, so we know what changed :).

**Comment by backnight** [comment]
Everything is ok ? Let me know if you need anything else.

**Comment by backnight** [comment]
About terraform fmt in main.tf file: the only change is the 2 conf vars added at the end.

**Comment by backnight** [comment]
Enjoy!

**Comment by backnight** [comment]
Up ?

**Comment by achille-roussel** [comment]
Looks good to me 👍 Thanks for your contribution.

**Pull request merged**
