### PR TITLE
Dockerfile for a tooling environment

### PR DESCRIPTION
**Pull request by gregwebs**
`make amis`, etc works from the container.

terraform isn't necessary for he make tasks, but could come in handy if you want to expand your usage of this environment.

### CODE REVIEW

**Comment by achille-roussel** [comment]
I like the idea but I'm not sure this belongs in this repository. There's nothing that is stack-specific in this dockerfile, it's more of a general-purpose container for working with packer and terraform.

Do you think it would be better on its own repository and we can show a link in the stack README?

**Comment by gregwebs** [comment]
Sorry for the late reply.

This is in fact specific to stack, its the only project I would use it on.

* designed to support python
* fills the Linux gap in the Makefile
* runs make install at setup

So you might consider if you want your open-source project to support Linux out-of-the box or if you think its fine for people to deal with issues of having the wrong version of Python, etc.

You can certainly point to my fork of stack. That will save you a file in the directory but cost you a line in your README.

**Comment by achille-roussel** [comment]
Fair, I'm happy to merge, just was thinking that any project that uses TF/Packer could benefit from having this container, not just stack-based stuff.

**Comment by gregwebs** [comment]
Its a good thought. In practice I find that containers (actually their images) compose very poorly at least at the level of building off of Dockerfiles. Even if you don't need to compose new things its often really hard to make them general enough for everyone also.

**Pull request merged**
