### PR TITLE
Task mount points

### PR DESCRIPTION
**Pull request by backnight**
Allow to set mount points for a task

### CODE REVIEW

**Comment by adambarthelson** [comment]
So... what happened to this?

**Comment by backnight** [comment]
When you specify a mount point, you need to be able te add a volume for your "aws_ecs_task_definition" and it's not possible in a module...

So as it is useless to add mount point without volume (they work together), this is why I deleted this pull request.

**Comment by adambarthelson** [comment]
Not possible in "a module", or in the modules provided by Segment's Stack?  I noticed that the service modules don't provide a way to specify volumes for each service, but I believe it could be tweaked in order to do so?

**Comment by backnight** [comment]
In the module provided by Segment's stack but I didn't find a solution to do it so...

Anyway, I think the Segment's task module is "useless" as it only creates a resource "aws_ecs_task_definition". If you want to create a task with volume or something special, just don't use the task module and make your own call to resource "aws_ecs_task_definition".

**Comment by adambarthelson** [comment]
Right, I was looking to extend Segment's service and task module in order to support volumes, that way we'd then be able to define related one-off tasks that can reference a service's volume to run against.

**Comment by achille-roussel** [comment]
Hey guys, the issue we faced with making volumes generic is terraform allows us to define this as a `volume` block on the task definition, which you cannot generate dynamically (this is what @backnight explained).

I believe the best way to go here is to fork or copy the task and service modules and tweak for your own use-case. This doesn't prevent you from using the rest of the modules, if you keep a compatible interface it'll be easy to integrate.

I hope that helped, it would really be awesome if terraform provided a more generic way of defining resources inner blocks.

**Comment by adambarthelson** [comment]
Yes, that was more or less what I was going to try to do.  Thanks!

**Pull request closed without merging**
