### PR TITLE
rds: support rds read replicas

### PR DESCRIPTION
**Pull request by tejasmanohar**
This just adds a replicate_source_db variable to the rds module
that proxies the setting to the TF RDS resource.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
This worked in terracode-warehouse (planned for both replica and primary)

**Comment by tejasmanohar** [comment]
@achille-roussel What version of TF do we need to support? I can bump `circle.yml` if that's ok with you. `make test` passes on v0.9.6 on my computer

**Comment by achille-roussel** [comment]
What's your concern on the version support? Are you using new features of 0.9.6? Supporting 0.9.x is good enough I think.

**Comment by tejasmanohar** [comment]
@achille-roussel I think ternaries may be new? `make test` passes locally but doesn't in CI so I assumed it was due to TF versioning

**Comment by achille-roussel** [comment]
Yes, ternaries are new in 0.8 I think, can you fix the test to run with a newer version of TF?
=> https://github.com/segmentio/stack/blob/master/circle.yml#L4

**Comment by tejasmanohar** [comment]
@achille-roussel Yep, just wanted to check that it's ok to upgrade :)

**Comment by achille-roussel** [comment]
@tejasmanohar what's the state of this PR?

**Pull request closed without merging**
