### PR TITLE
fix ecs cluster name

### PR DESCRIPTION
**Pull request by SKAhack**

### CODE REVIEW

**Comment by yields** [comment]
Thanks for the PR,

can you elaborate more about what you're trying to do please?

because i think this one is intentionally named `"default"`, if you want to change the default cluster name i think we should add another variable instead, say `ecs_cluster_name` and default it's value to `"default"` so it's a bit more clear.

**Comment by SKAhack** [comment]
Thanks for your comment.

just a question. how do I has two or more cluster?

> i think we should add another variable instead, say ecs_cluster_name and default it's value to "default" so it's a bit more clear.

sounds good to me.

( I trying to make a docker container cluster lately. because I don't know a lot about ECS... )

**Comment by yields** [comment]
> just a question. how do I has two or more cluster?

Oh just use the cluster module directly, like the one defined in [`stack/main.tf`](https://github.com/segmentio/stack/blob/e51e3438ae74c8deca13168042e672454ee40ca8/main.tf#L170) and set the name to whatever you want :)

Simple example:

```tf
module "my_cluster" {
  source      = "github.com/segmentio/stack/ecs-cluster"
  environment = "prod"
  name        = "my-cluster"
}
```

**Comment by SKAhack** [comment]
Thank you. I was wrong 👻

**Pull request closed without merging**
