### PR TITLE
Correctly set the cluster name

### PR DESCRIPTION
**Pull request by backnight**
Hello again,

Actually, the created cluster has the name "default".
This pull request set the cluster name based on the main stack name.

Have a nice day!

### CODE REVIEW

**Comment by achille-roussel** [comment]
The changes look good to me. I'm a bit concerned that the ECS cluster name isn't managed independently from the stack name, what would you think about doing something like this:
```hcl
variable "ecs_cluster_name" {
    default = ""
}
...
name = "${coalesce(var.ecs_cluster_name, var.name)}"
```
?

**Comment by backnight** [comment]
Okay for me, I will do the modifications.

**Comment by backnight** [comment]
Let me know if it's okay for you know.

Have a good day!

**Comment by achille-roussel** [comment]
Looks great :+1: thanks for your contributions!

**Pull request merged**
